### ISSUE TITLE
[3pt] Preserve Game & Author's data

### ISSUE THREAD

**Issue by yosefHesham** [yosefHesham/Catalog-My-Things#13]
- All data should be preserved by saving collections in .json files.

- Create a schema.sql file with tables that will be analogical to the structure of the classes that you created: games table (add all properties and associations from the parent Item class as table columns)
authors table

**Comment by vanelnw** [comment]
- All data should be preserved by saving collections in .json files.

- Create a schema.sql file with tables that will be analogical to the structure of the classes that you created: games table (add all properties and associations from the parent Item class as table columns)
authors table
